%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

%global __cmake_in_source_build 1

Name:           ros-rolling-message-filters
Version:        7.3.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS message_filters package

License:        BSD
URL:            https://github.com/ros2/message_filters
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-rolling-builtin-interfaces
Requires:       ros-rolling-rclcpp
Requires:       ros-rolling-rclpy
Requires:       ros-rolling-rcutils
Requires:       ros-rolling-std-msgs
Requires:       ros-rolling-ros-workspace
BuildRequires:  ros-rolling-ament-cmake-python
BuildRequires:  ros-rolling-ament-cmake-ros
BuildRequires:  ros-rolling-rclcpp
BuildRequires:  ros-rolling-rcutils
BuildRequires:  ros-rolling-std-msgs
BuildRequires:  ros-rolling-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-rolling-ament-cmake-gtest
BuildRequires:  ros-rolling-ament-cmake-pytest
BuildRequires:  ros-rolling-ament-lint-auto
BuildRequires:  ros-rolling-ament-lint-common
BuildRequires:  ros-rolling-rclcpp-lifecycle
BuildRequires:  ros-rolling-sensor-msgs
%endif

%description
A set of ROS 2 message filters which take in messages and may output those
messages at a later time, based on the conditions that filter needs met.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/rolling" \
    -DAMENT_PREFIX_PATH="/opt/ros/rolling" \
    -DCMAKE_PREFIX_PATH="/opt/ros/rolling" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/rolling

%changelog
* Fri Oct 03 2025 Geoffrey Biggs <geoff@openrobotics.org> - 7.3.2-1
- Autogenerated by Bloom

* Wed Sep 17 2025 Geoffrey Biggs <geoff@openrobotics.org> - 7.3.1-1
- Autogenerated by Bloom

* Tue Jul 29 2025 Geoffrey Biggs <geoff@openrobotics.org> - 7.3.0-1
- Autogenerated by Bloom

* Tue Jul 01 2025 Geoffrey Biggs <geoff@openrobotics.org> - 7.2.2-1
- Autogenerated by Bloom

* Wed May 14 2025 Geoffrey Biggs <geoff@openrobotics.org> - 7.2.1-1
- Autogenerated by Bloom

* Tue Apr 08 2025 Geoffrey Biggs <geoff@openrobotics.org> - 7.1.0-1
- Autogenerated by Bloom

* Thu Mar 13 2025 Geoffrey Biggs <geoff@openrobotics.org> - 7.0.2-1
- Autogenerated by Bloom

* Fri Jan 31 2025 Geoffrey Biggs <geoff@openrobotics.org> - 7.0.1-1
- Autogenerated by Bloom

* Fri Dec 20 2024 Geoffrey Biggs <geoff@openrobotics.org> - 7.0.0-1
- Autogenerated by Bloom

* Wed Nov 20 2024 Geoffrey Biggs <geoff@openrobotics.org> - 6.0.7-1
- Autogenerated by Bloom

* Wed Oct 16 2024 Geoffrey Biggs <geoff@openrobotics.org> - 6.0.6-1
- Autogenerated by Bloom

* Thu Oct 03 2024 Geoffrey Biggs <geoff@openrobotics.org> - 6.0.5-1
- Autogenerated by Bloom

* Mon Aug 19 2024 Geoffrey Biggs <geoff@openrobotics.org> - 6.0.4-1
- Autogenerated by Bloom

* Wed Jul 31 2024 Geoffrey Biggs <geoff@openrobotics.org> - 6.0.3-1
- Autogenerated by Bloom

* Mon Jul 29 2024 Geoffrey Biggs <geoff@openrobotics.org> - 6.0.2-1
- Autogenerated by Bloom

* Fri Jul 19 2024 Geoffrey Biggs <geoff@openrobotics.org> - 6.0.1-1
- Autogenerated by Bloom

* Wed Jun 26 2024 Geoffrey Biggs <geoff@openrobotics.org> - 6.0.0-1
- Autogenerated by Bloom

* Mon Jun 17 2024 Geoffrey Biggs <geoff@openrobotics.org> - 5.0.0-1
- Autogenerated by Bloom

* Fri Apr 26 2024 Geoffrey Biggs <geoff@openrobotics.org> - 4.12.0-1
- Autogenerated by Bloom

* Tue Apr 16 2024 Geoffrey Biggs <geoff@openrobotics.org> - 4.11.1-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Geoffrey Biggs <geoff@openrobotics.org> - 4.11.0-2
- Autogenerated by Bloom

